# Generated by Django 5.1.3 on 2024-11-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='student',
        ),
    ]
