# Generated by Django 5.1.3 on 2024-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_register_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('depatment', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('attendance', models.CharField(max_length=20)),
                ('backlog', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
