# Generated by Django 5.1.3 on 2024-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_room_nomination_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='regno',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
