# Generated by Django 5.1.3 on 2024-11-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_nomination_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='policy1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='policy2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='policy3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
