# Generated by Django 5.1.3 on 2024-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_candidate_avatar_candidate_policy1_candidate_policy2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
