# Generated by Django 5.1.3 on 2024-11-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_candidate_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
    ]
