# Generated by Django 5.1.3 on 2024-11-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_candidate_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairperson_votes', to='app.candidate')),
                ('fine_arts_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_arts_secretary_votes', to='app.candidate')),
                ('general_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_secretary_votes', to='app.candidate')),
                ('joint_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secretary_votes', to='app.candidate')),
                ('student_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_editor_votes', to='app.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('uuc_rep_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uuc_rep_1_votes', to='app.candidate')),
                ('uuc_rep_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uuc_rep_2_votes', to='app.candidate')),
                ('vice_chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_chairperson_votes', to='app.candidate')),
            ],
        ),
    ]
