# Generated by Django 5.1.4 on 2024-12-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_candidate_course_alter_candidate_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('description', models.TextField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_posts', to='app.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.candidate')),
            ],
        ),
    ]
