# Generated by Django 5.1.4 on 2025-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_candidate_candidateid_alter_candidate_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
