# Generated by Django 5.1.4 on 2025-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_nomination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='phoneno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
