# Generated by Django 5.1.3 on 2025-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_nomination_course_alter_nomination_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='regno',
            field=models.CharField(max_length=20),
        ),
    ]
