# Generated by Django 5.1.3 on 2025-02-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_nomination_reason_alter_nomination_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='regno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
