# Generated by Django 5.1.3 on 2025-02-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_nomination_studentid_nomination_tutor_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='tutor_in_charge',
        ),
    ]
