# Generated by Django 5.1.3 on 2025-02-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_nomination_studentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='studentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomination',
            name='tutor_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='app.faculty'),
            preserve_default=False,
        ),
    ]
