# Generated by Django 5.1.3 on 2025-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_nomination_studentid_nomination_tutor_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
