# Generated by Django 5.1.3 on 2025-02-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_votingsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotingSettings',
        ),
    ]
